GET http://localhost:9999/api/posts

###

GET http://localhost:9999/api/posts/3

###

POST http://localhost:9999/api/posts
Content-Type: application/json

{
  "id": 0,
  "content": "Last Post",
  "removed": false
}

###

POST http://localhost:9999/api/posts
Content-Type: application/json

{
  "id": 3,
  "content": "Edit Post",
  "removed": false
}

###

DELETE http://localhost:9999/api/posts/3
